name: Build

on:
  # Run on each pull request
  pull_request:
  # Run on a push to the main branch
  push:
    branches:
      - main
  # Run when a release is published
  release:
    types:
      - published

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Install Roc
        uses: hasnep/setup-roc@main
        with:
          roc-version: nightly
      - name: Install Rust
        uses: actions/setup-rust@v1
      - name: Build the platform
        run: roc build.roc
      - name: Bundle and release the platform
        uses: hasnep/bundle-roc-library@v0.1.0
        with:
          library: platform/main.roc
          token:  ${{ github.token }}